import Head from "next/head";
import { MdDarkMode } from "react-icons/md";
import Image from "next/image";
import ankit from "../public/profile1.png";
import Typewriter from "typewriter-effect";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { useState } from "react";

export default function Home() {
  const [darktheme, setDarkTheme] = useState(false);

  return (
    <div className={darktheme ? "dark" : ""}>
      <Head>
        <title>Ankit Kumar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="min-h-screen dark:bg-slate-800 dark:text-white">
          <nav className=" text-xl mb-10  p-10 pb-0 flex justify-between items-center">
            <div>
              <h1 className="font-burtons md:text-3xl">Ankit Kumar</h1>
            </div>
            <ul className="flex items-center">
              <li className="mr-2" onClick={() => setDarkTheme(!darktheme)}>
                <MdDarkMode className="text-2xl cursor-pointer"></MdDarkMode>
              </li>
              <li>
                <a
                  href="./resume.pdf"
                  className="text-white bg-gradient-to-r from-cyan-500 to-teal-500  py-2 px-4
                  rounded-md"
                  target="_blank"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="p-10 text-center ">
            <h2 className="text-5xl font-bold mb-4">
              <Typewriter
                onInit={(typewriter) => {
                  typewriter
                    .typeString("Hi, I'm Ankit Kumar!")
                    .pauseFor(2000)
                    .deleteChars(12)
                    .typeString("a Frontend developer")
                    .start();
                }}
              />
            </h2>
            <h3 className="mb-4 text-lg italic dark:text-slate-400">
              Frontend Developer!!!
            </h3>
            <p className=" leading-6 px-10 max-w-lg mx-auto dark:text-slate-400">
              Front End developer skilled in making responsive UI using HTML5,
              CSS3, Javascript, React js, Restful API. Have a passion to learn
              and implement.
            </p>
          </div>
          <div className="flex justify-center gap-16 text-4xl text-slate-600 mb-10 ">
            <a href="#">
              <AiFillLinkedin className="hover:text-black dark:hover:text-white"></AiFillLinkedin>
            </a>
            <a href="#">
              <AiFillTwitterCircle className="hover:text-black dark:hover:text-white"></AiFillTwitterCircle>
            </a>
            <a href="#">
              <AiFillGithub className="hover:text-black dark:hover:text-white"></AiFillGithub>
            </a>
          </div>
          <div className="w-64 h-64 mx-auto rounded-full overflow-hidden">
            <Image src={ankit}></Image>
          </div>
        </section>
      </main>
    </div>
  );
}
